# Публичные настройки БД (БЕЗ паролей - безопасно коммитить в Git)
db.url=jdbc:postgresql://localhost:5432/mentee_db
db.username=mentee
db.driver=org.postgresql.Driver

# Дополнительные настройки
app.name=mp-sql-api
db.show-sql=true